---
title: "Final Project Template"
author: Dr. Sandholtz
output: pdf_document
---

<style type="text/css">
h1.title {
font-size: 40px;
text-align: center;
}
h4.author {
font-size: 40px;
text-align: center;
}
</style>

\newpage

```{r setup, include=FALSE}

```

# Abstract

There is no institution in modern day politics more important than elections. Regardless of whether a regime is democratic (where elections are free and fair) or autocratic, election are a staple of today's political world, providing (some) legitimacy to those who win them. Thus, one of the central puzzles in the social sciences is why some parties win more votes than others. In this paper, we fit several statistical models to predict party vote share, finding that party strength is the best predictor of a party's success in elections.

# 1 Problem and Motivation

There is no institution in modern day politics more important than elections. Since the 1990's almost every country in the world has switched to using elections to decide which party or candidate is in government. Even in autocratic regimes like modern day China and Russia use elections to justify the incumbents' stays in power, even if the results are pre-determined. 

Given the importance of elections, tools and variables that predict elections are valuable. In this paper, we create several statistical models that predict the vote share of elections' primary actors: political parties. In doing so, we identify several factors that strongly influence voter share. Additionally, we explore how the effect of various predictors of vote share change depending on the level of democracy in the country.

## 1.1 Data Description

To fit our models, we use data from the Varieties of Democracy database (V-Dem). V-Dem is the largest database on democracy and parties in the world, covering country-level democracy data in every country from 1789 to now and party-level data from 1970 to now. Every variable we use in our data comes from V-Dem, allowing us to cover over 3000 parties in 165 countries over the a 50 year period. For our models, our unit of analysis is party-year. For example, the United States Republican Party in 2000 is an observation in our analysis.

We consider several predictors of party vote share. Regarding party factors, we include measures of ideology (left-right), anti-pluralism, if the party is a pariah, party brand continuity, and party strength. We also include several country factors, including, compulsory voting, election type, and quality of democracy. 

Because of scholars recent focus on party strength (i.e., the party's organizational capacity to mobilize its voters), we are particularly interested in it effect.

For our dependent variable, we use a parties raw vote percentage and multiply it by the registered voter turnout. We do this for easier comparison between cases, as we expect some parties to not only increase their raw vote share, but to encourage higher voter turnout.

## 1.2 Questions of Interest

We are interested in two questions. First, what variables best predict the a party's vote share? A branch of this question is what is the effect of party strength on party vote share?

The second question is related two the first. How does the relationship between party strength and vote share change given the countries level of democracy?

## 1.3 Regression Methods

Two answer the first question, we use forward, backward, and sequential stepwise model selection to choose our predictors. After checking assumptions, re-selecting variables, and transforming our variables to meet the regression assumptions, we came to this formula:

***SOMEONE MAKE THIS LATEX***
(1/vote share) ~ Party Strength + Compulsory Voting + Ideology + Democracy Score + Anti_Pluralism + Pariah + Party Brand Constinutiy


# 2 Analyses, Results, and Interpretation

Conduct the analysis in a logical fashion, including necessary code (and not any superfluous code) and its output. Give simple interpretations of your findings related to the questions of interest.


  As mentioned in the regression methods subsection, we utilize forward, backward, and sequential stepwise model selection in order to find the variables that have an effect on party vote share. The result tells us that the best predictors of party vote share are: party strength, compulsory voting, ideology, democracy score, anti-pluralism, pariah, and party brand continuity. Using these selected predictors, we create a model and check the model assumptions. A historgram of the response variable appears skewed. To remedy this, we apply a Box Cox transformation and rerun the stepwise function. 
  We check the assumptions again. A residual-fitted value plot reveals that linearity is satisfied. The normal Q-Q plot and the Shapiro-Wilkes test tell us that our errors are not perfectly normal, but much more normal than our previous models. The scale-location plot indicates that there is little to no heterogeneity. Cook's distance indicate an absence of any influential points. Lastly, the VIF results show a lack of collinearity.
  Satisfied by the model, we may begin to make inference. We plot the mean effect of each of our variables and the 95% confidence interval for their respective effects. We find that party strength has the highest predicted effect on vote share of all the predictors in our model. Compulsory vote and left wing both have positive, significant effects. Meanwhile, pariah, reformed party, anti-pluralist, same party, and democracy all have negative effects on vote share.
  In studying the effect of party strength on vote share given different levels of democracy, we began by plotting the vote share against party strength and added a color scale to indicate the levels of democracy for each observation. We plot the average predicted effects of party strength on voter share at three different levels of democracy, at the 2.5, 50, and 97.5 percentiles level. he result shows that clearly the effect decreases as the percentile of democracy increases.


# 3 Conclusions

Give additional context to you results and interpretations from Section 5 with respect to the data set and its purpose.  Describe any potential weaknesses in your analysis, and how they may affect the reliability of the results.

# 4 Contributions

For each member of the group, write a short paragraph describing their contribution to this project and the report.  It is up to you to decide how to divide up the work, so long as everyone is contributing approximately equally. 

## APPENDIX

If there are any analyses, such as exploratory plots/summaries or work you did to determine appropriate transformations, or any relevant material that does not belong in one of the sections above, these can go in the Appendix.  If you don't have any material like this, you can remove this section.


